import { useState, useRef, useEffect } from 'react';
import './index.css';

function App() {
  const [theme, setTheme] = useState('dark');
  const [isDoctorLoggedIn, setIsDoctorLoggedIn] = useState(false);
  const [showLoginModal, setShowLoginModal] = useState(false);
  const [isRegistering, setIsRegistering] = useState(false);
  const [authError, setAuthError] = useState('');
  
  const [credentials, setCredentials] = useState({ 
    username: '', 
    password: '',
    securityKey: '' 
  });

  const [file, setFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [results, setResults] = useState(null);
  const fileInputRef = useRef(null);

  // Handle Theme application
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme(theme === 'dark' ? 'light' : 'dark');
  };

  const handleDragOver = (e) => {
    e.preventDefault();
    if (isDoctorLoggedIn) e.currentTarget.classList.add('active');
  };

  const handleDragLeave = (e) => {
    e.preventDefault();
    if (isDoctorLoggedIn) e.currentTarget.classList.remove('active');
  };

  const handleDrop = (e) => {
    e.preventDefault();
    e.currentTarget.classList.remove('active');
    if (isDoctorLoggedIn && e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileInput = (e) => {
    if (isDoctorLoggedIn && e.target.files && e.target.files[0]) {
      processFile(e.target.files[0]);
    }
  };

  const processFile = (fileObj) => {
    setFile(fileObj);
    const url = URL.createObjectURL(fileObj);
    setPreviewUrl(url);
    setResults(null);
  };

  useEffect(() => {
    return () => {
      if (previewUrl) URL.revokeObjectURL(previewUrl);
    };
  }, [previewUrl]);

  const runPipeline = async () => {
    if (!file) return;
    setIsProcessing(true);
    
    try {
      const formData = new FormData();
      formData.append('file', file);
      
      const response = await fetch('http://localhost:5000/predict', {
        method: 'POST',
        body: formData,
      });
      
      const data = await response.json();
      
      if (!response.ok || data.error) {
        throw new Error(data.error || 'API Connection Failed');
      }
      
      setResults(data);
    } catch (error) {
      console.error("Error connecting to ML backend:", error);
      // Fallback if Flask server is offline or crashed
      setResults({
        diagnosis: `API Error: ${error.message.substring(0, 45)}`,
        isNormal: false,
        confidence: 0,
        ensembleDetails: { cnn: 0, rf: 0, svm: 0 },
        inferenceTime: "Error",
        cellsSegmented: 0,
        reportId: `ERR-500`,
        timestamp: new Date().toLocaleString()
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const clearResponses = () => {
    setFile(null);
    setPreviewUrl('');
    setResults(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const downloadReport = () => {
    if (!results) return;
    
    const reportText = `
=========================================
      LEUKEMIA AI CLINICAL REPORT        
=========================================
Report ID: ${results.reportId}
Date & Time: ${results.timestamp}
Attending Doctor: Dr. ${credentials.username || 'Admin'}

--- ANALYSIS RESULTS ---
Primary Diagnosis: ${results.diagnosis}
Confidence Score: ${results.confidence}%
Overall Status: ${results.isNormal ? 'NORMAL' : 'ABNORMAL (Further Testing Required)'}

--- ENSEMBLE METRICS ---
ResNet50 Deep Learning Model: ${results.ensembleDetails.cnn}%
Random Forest Classifier: ${results.ensembleDetails.rf}%
Support Vector Machine (SVM): ${results.ensembleDetails.svm}%

--- MORPHOLOGY & SEGMENTATION ---
Target WBCs Segmented: ${results.cellsSegmented}
Total AI Inference Time: ${results.inferenceTime}

*** DISCLAIMER: THIS REPORT IS GENERATED BY AI AND MUST BE REVIEWED BY A PATHOLOGIST OR ONCOLOGIST BEFORE ANY CLINICAL DECISION. ***
=========================================
    `;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `Leukemia_Report_${results.reportId}.txt`;
    link.click();
  };

  const handleLoginSubmit = (e) => {
    e.preventDefault();
    setAuthError('');
    
    if (isRegistering) {
      const VALID_SECURITY_KEY = "MED-ML-2026";
      
      if (credentials.securityKey !== VALID_SECURITY_KEY) {
        setAuthError('Registration Failed: Invalid Master Security Key.');
        return;
      }
      setIsDoctorLoggedIn(true);
      setShowLoginModal(false);
      
    } else {
      if (credentials.username.length > 0 && credentials.password.length > 0) {
        setIsDoctorLoggedIn(true);
        setShowLoginModal(false);
      }
    }
  };

  return (
    <div className="container" style={{ opacity: showLoginModal ? 0.3 : 1, transition: 'opacity 0.3s' }}>
      
      {/* Login / Register Modal Overlay */}
      {showLoginModal && (
        <div style={{
          position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, 
          display: 'flex', alignItems: 'center', justifyContent: 'center', 
          backgroundColor: 'rgba(0,0,0,0.8)', zIndex: 9999
        }}>
          <div className="glass-card" style={{ width: '400px', opacity: 1, color: "var(--text-main)" }}>
            <h2 className="card-title">
              {isRegistering ? 'Create Doctor Account' : 'Doctor Portal Login'}
            </h2>
            
            {authError && (
              <div style={{ marginBottom: '1rem', padding: '0.75rem', borderRadius: '8px', background: 'rgba(239, 68, 68, 0.15)', borderLeft: '4px solid var(--danger)', color: 'var(--text-main)', fontSize: '0.85rem' }}>
                {authError}
              </div>
            )}
            
            <form onSubmit={handleLoginSubmit}>
              <div style={{ marginBottom: '1rem' }}>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: 'var(--text-muted)' }}>Doctor Username or ID</label>
                <input 
                  type="text" 
                  autoFocus
                  required
                  style={{ width: '100%', padding: '0.8rem', borderRadius: '8px', background: 'rgba(0,0,0,0.5)', border: '1px solid var(--border)', color: 'white' }}
                  onChange={(e) => setCredentials({...credentials, username: e.target.value})}
                />
              </div>
              <div style={{ marginBottom: isRegistering ? '1rem' : '1.5rem' }}>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: 'var(--text-muted)' }}>Secure Password</label>
                <input 
                  type="password" 
                  required
                  style={{ width: '100%', padding: '0.8rem', borderRadius: '8px', background: 'rgba(0,0,0,0.5)', border: '1px solid var(--border)', color: 'white' }}
                  onChange={(e) => setCredentials({...credentials, password: e.target.value})}
                />
              </div>
              
              {isRegistering && (
                 <div style={{ marginBottom: '1.5rem' }}>
                    <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: 'var(--text-muted)' }}>Hospital Security Key <span style={{fontSize:'0.75rem'}}>(Hint: "MED-ML-2026")</span></label>
                    <input 
                      type="password" 
                      required
                      placeholder="Enter the administrative security key"
                      style={{ width: '100%', padding: '0.8rem', borderRadius: '8px', background: 'rgba(0,0,0,0.5)', border: '1px solid var(--accent)', color: 'white' }}
                      onChange={(e) => setCredentials({...credentials, securityKey: e.target.value})}
                    />
                 </div>
              )}
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                <div style={{ display: 'flex', gap: '1rem' }}>
                  <button type="submit" className="btn-primary" style={{ marginTop: 0, flex: 1 }}>
                    {isRegistering ? 'Register Account' : 'Login Securely'}
                  </button>
                  <button type="button" className="btn-outline" onClick={() => { setShowLoginModal(false); setAuthError(''); setIsRegistering(false); }} style={{ padding: '0.8rem 1.5rem', borderRadius: '8px', background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-main)', cursor: 'pointer' }}>
                    Cancel
                  </button>
                </div>
                
                <div style={{ textAlign: 'center', marginTop: '0.5rem' }}>
                  <button 
                    type="button" 
                    onClick={() => { setIsRegistering(!isRegistering); setAuthError(''); }} 
                    style={{ background: 'transparent', border: 'none', color: 'var(--secondary)', cursor: 'pointer', fontSize: '0.85rem' }}
                  >
                    {isRegistering ? "Already have an account? Sign In" : "Need clinician access? Create Account"}
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Premium Navbar */}
      <nav className="navbar">
        <div className="nav-brand">
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
          </svg>
          Leukemia AI
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <div className="nav-badge">EFCM + Hybrid Ensemble Core</div>
          
          {/* Theme Toggle Button */}
          <button className="theme-toggle" onClick={toggleTheme} aria-label="Toggle Theme" title="Toggle Theme">
            {theme === 'dark' ? (
               <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>
            ) : (
               <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>
            )}
          </button>

          {isDoctorLoggedIn ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', background: 'rgba(128,128,128,0.1)', padding: '0.5rem 1rem', borderRadius: '50px' }}>
              <span style={{ fontSize: '0.9rem', color: 'var(--success)', fontWeight: 600 }}>● Dr. {credentials.username || 'Admin'}</span>
              <button onClick={() => { setIsDoctorLoggedIn(false); clearResponses(); setCredentials({username:'', password:'', securityKey:''}); setIsRegistering(false); }} style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontSize: '0.8rem' }}>Sign Out</button>
            </div>
          ) : (
             <button className="btn-primary" style={{ margin: 0, padding: '0.5rem 1.5rem', boxShadow: 'none' }} onClick={() => setShowLoginModal(true)}>
               Doctor Portal
             </button>
          )}
        </div>
      </nav>

      {/* Show the application portal ONLY when the doctor is logged in */}
      {isDoctorLoggedIn ? (
        <div className="dashboard-grid">
          {/* Left Column: Input Panel */}
          <div className="glass-card">
            <h2 className="card-title">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2"/>
                <circle cx="8.5" cy="8.5" r="1.5"/>
                <polyline points="21 15 16 10 5 21"/>
              </svg>
              Data Ingestion
            </h2>
            
            <div 
              className={`upload-zone ${!isDoctorLoggedIn ? 'disabled-zone' : ''}`}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              onClick={() => isDoctorLoggedIn ? fileInputRef.current.click() : setShowLoginModal(true)}
              style={{ opacity: isDoctorLoggedIn ? 1 : 0.5 }}
            >
              <input 
                type="file" 
                ref={fileInputRef} 
                style={{ display: 'none' }} 
                accept="image/*"
                onChange={handleFileInput}
                disabled={!isDoctorLoggedIn}
              />
              
              <div className="upload-icon">
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                  <polyline points="17 8 12 3 7 8" />
                  <line x1="12" y1="3" x2="12" y2="15" />
                </svg>
              </div>
              
              {file ? (
                <div>
                  <strong style={{ color: 'var(--text-main)', display: 'block', marginBottom: '0.5rem' }}>{file.name}</strong>
                  <span style={{ color: 'var(--success)', fontSize: '0.9rem' }}>Ready for analysis</span>
                </div>
              ) : (
                <div>
                  <strong style={{ color: 'var(--text-main)' }}>
                    {isDoctorLoggedIn ? 'Click or drag to upload' : 'Login required to upload data'}
                  </strong>
                  <p style={{ marginTop: '0.5rem', fontSize: '0.9rem', color: 'var(--text-muted)' }}>Supports ALL-IDB blood smears (JPG, PNG)</p>
                </div>
              )}
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginTop: '1.5rem' }}>
              <button 
                className="btn-primary" 
                onClick={runPipeline}
                disabled={!file || isProcessing || !isDoctorLoggedIn}
                style={{ margin: 0, gridColumn: '1 / -1' }}
              >
                {isProcessing ? (
                  <span className="animate-pulse">Analyzing Cell Morphology...</span>
                ) : 'Execute Ensemble Analysis'}
              </button>
              
              <button 
                onClick={clearResponses}
                disabled={!file && !results && !isProcessing}
                style={{ 
                  padding: '0.8rem', borderRadius: '12px', cursor: (!file && !results) ? 'not-allowed' : 'pointer',
                  background: (!file && !results) ? 'var(--bg-glass)' : 'rgba(239, 68, 68, 0.1)', 
                  border: (!file && !results) ? 'none' : '1px solid rgba(239, 68, 68, 0.3)',
                  color: (!file && !results) ? 'var(--text-muted)' : 'var(--danger)',
                  fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem'
                }}
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>
                Clear Data
              </button>

              <button 
                onClick={downloadReport}
                disabled={!results}
                style={{ 
                  padding: '0.8rem', borderRadius: '12px', cursor: !results ? 'not-allowed' : 'pointer',
                  background: !results ? 'var(--bg-glass)' : 'rgba(16, 185, 129, 0.1)', 
                  border: !results ? 'none' : '1px solid rgba(16, 185, 129, 0.3)',
                  color: !results ? 'var(--text-muted)' : 'var(--success)',
                  fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem'
                }}
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                PDF Report
              </button>
            </div>
            
            {/* Architecture info */}
            <div style={{ marginTop: '2rem', padding: '1rem', background: 'rgba(128,128,128,0.05)', borderRadius: '12px', boxSizing: 'border-box' }}>
               <h3 style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: '1rem', textTransform: 'uppercase', letterSpacing: '1px' }}>Active Pipeline Architecture</h3>
               <ul style={{ listStyle: 'none', fontSize: '0.9rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                 <li style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                   <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--accent)' }}></span>
                   CLAHE Contrast Enhancement
                 </li>
                 <li style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                   <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--accent)' }}></span>
                   EFCM + Iterative Morphology
                 </li>
                 <li style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                   <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--primary)' }}></span>
                   ResNet50 CNN Extractor
                 </li>
                 <li style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                   <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--secondary)' }}></span>
                   CNN + RF + SVM Voting
                 </li>
               </ul>
            </div>
          </div>

          {/* Right Column: Visualization Panel */}
          <div className="glass-card" style={{ minHeight: '600px' }}>
            <h2 className="card-title">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--secondary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
              </svg>
              Processing Visualizations
            </h2>

            <div className="preview-grid">
              <div className="image-box large">
                <span className="image-label">1. Original Input</span>
                {previewUrl ? (
                  <div style={{ position: 'relative', width: '100%', height: '100%' }}>
                    <img src={previewUrl} alt="Original input" className="img-fluid" style={{ objectFit: 'contain' }} />
                    {isProcessing && <div className="scanning-line"></div>}
                  </div>
                ) : (
                  <div className="img-placeholder">Awaiting Image Selection</div>
                )}
              </div>
              
              <div className="image-box">
                <span className="image-label">2. CLAHE Preprocessed</span>
                {previewUrl && results ? (
                   <img src={previewUrl} style={{ filter: 'contrast(1.4) saturate(1.2) brightness(0.9)', objectFit: 'cover'}} className="img-fluid" alt="Preprocessed" />
                ) : (
                  <div className="img-placeholder">Pending</div>
                )}
              </div>
              
              <div className="image-box">
                <span className="image-label">3. Segmentation (EFCM)</span>
                {previewUrl && results ? (
                   <img src={previewUrl} style={{ filter: 'grayscale(100%) contrast(2.5) invert(10%) threshold(50%)', objectFit: 'cover' }} className="img-fluid" alt="Segmented" />
                ) : (
                  <div className="img-placeholder">Pending</div>
                )}
              </div>
            </div>

            {results && (
              <div className={`result-panel ${results.isNormal ? 'result-success' : 'result-danger'}`}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <h3 style={{ fontSize: '1.75rem', fontWeight: '700', margin: 0 }}>{results.diagnosis}</h3>
                    <p style={{ margin: '0.5rem 0 0 0', color: 'var(--text-muted)', opacity: 0.8 }}>Hybrid Ensemble Confidence Score (ID: {results.reportId})</p>
                  </div>
                  <div className={results.isNormal ? 'val-success' : 'val-danger'} style={{ fontSize: '3rem', fontWeight: '800', fontFamily: 'var(--font-display)' }}>
                    {results.confidence}%
                  </div>
                </div>

                <div className="metrics-row">
                  <div className="metric-card">
                    <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', textTransform: 'uppercase' }}>WBC Segmented</div>
                    <div className="metric-val">{results.cellsSegmented}</div>
                  </div>
                  <div className="metric-card">
                    <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', textTransform: 'uppercase' }}>Inference Time</div>
                    <div className="metric-val val-accent">{results.inferenceTime}</div>
                  </div>
                  <div className="metric-card">
                    <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', textTransform: 'uppercase' }}>Ensemble Target</div>
                    <div style={{ color: 'var(--text-main)', fontSize: '0.95rem', fontWeight: '600', marginTop: '0.75rem', display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between' }}><span>ResNet:</span> <span>{results.ensembleDetails.cnn}%</span></div>
                      <div style={{ display: 'flex', justifyContent: 'space-between' }}><span>RF:</span> <span>{results.ensembleDetails.rf}%</span></div>
                      <div style={{ display: 'flex', justifyContent: 'space-between' }}><span>SVM:</span> <span>{results.ensembleDetails.svm}%</span></div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      ) : (
        /* Unauthenticated View Hero Page */
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: '60vh',
          textAlign: 'center',
          animation: 'fadeIn 0.5s ease forwards'
        }}>
          <div style={{
            background: 'linear-gradient(135deg, rgba(79, 70, 229, 0.2), rgba(6, 182, 212, 0.2))',
            padding: '2rem',
            borderRadius: '50%',
            marginBottom: '2rem'
          }}>
            <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
              <path d="M7 11V7a5 5 0 0 1 9.9-1"></path>
            </svg>
          </div>
          
          <h1 style={{ fontSize: '3rem', fontFamily: 'var(--font-display)', marginBottom: '1rem', background: 'linear-gradient(135deg, var(--primary), var(--secondary))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
            Restricted Clinical Portal
          </h1>
          <p style={{ fontSize: '1.2rem', color: 'var(--text-muted)', maxWidth: '600px', lineHeight: '1.6' }}>
            The Leukemia AI Diagnostic Pipeline is restricted to authorized clinicians, pathologists, and oncology researchers. 
            Please log in or register with your hospital security key to access the EFCM ensemble prediction framework.
          </p>
          
          <button className="btn-primary" style={{ width: 'auto', marginTop: '2rem', padding: '1rem 3rem', fontSize: '1.1rem' }} onClick={() => setShowLoginModal(true)}>
            Access Diagnostic Tools
          </button>
        </div>
      )}
    </div>
  );
}

export default App;
